stages:
  - test
  - build
  - deploy

variables:
  GOOGLE_PROJECT_ID: "northern-shield-453920-a4" # Не менять!
  GOOGLE_COMPUTE_ZONE: "us-central1-a" # Не менять!
  DOCKER_DRIVER: overlay2
  VM_NAME: "web-server"
  SA_EMAIL: "grit-provisioner-auto@northern-shield-453920-a4.iam.gserviceaccount.com"

test:
  stage: test
  image: python:3.11
  script:
    - pip install -r requirements.txt
    - python -m pytest

build:
  stage: build
  image: python:3.11
  script:
    - pip install -r requirements.txt
    - python setup.py build
  artifacts:
    paths:
      - build/
      - dist/
      - requirements.txt

deploy:
  stage: deploy
  image: google/cloud-sdk:latest
  before_script:
    - echo "$GOOGLE_CLOUD_KEY" > /tmp/google-cloud-key.json
    - export GOOGLE_APPLICATION_CREDENTIALS=/tmp/google-cloud-key.json
    - gcloud auth activate-service-account --quiet --key-file=$GOOGLE_APPLICATION_CREDENTIALS
    - gcloud config set project $GOOGLE_PROJECT_ID --quiet
  script:
    - SA_USERNAME="sa_$(echo $SA_EMAIL | cut -d@ -f1)"
    - gcloud compute os-login describe-profile --quiet
    - gcloud compute scp --quiet --recurse ./dist/* $SA_USERNAME@$VM_NAME:/home/$SA_USERNAME/kafka-test/ --zone=$GOOGLE_COMPUTE_ZONE --tunnel-through-iap
    - gcloud compute ssh --quiet $SA_USERNAME@$VM_NAME --zone=$GOOGLE_COMPUTE_ZONE --tunnel-through-iap --command="cd /home/$SA_USERNAME/kafka-test && pip install -r requirements.txt && python setup.py install"
  only:
    - main 