stages:
  - test
  - build
  - deploy

variables:
  GOOGLE_PROJECT_ID: "northern-shield-453920-a4" # Не менять!
  GOOGLE_COMPUTE_ZONE: "us-central1-a" # Не менять!
  DOCKER_DRIVER: overlay2
  VM_NAME: "web-server"
  SA_EMAIL: "grit-provisioner-auto@northern-shield-453920-a4.iam.gserviceaccount.com"
  
test:
  stage: test
  image: python:3.11
  script:
    - pip install -r requirements.txt
    - python -m pytest

build:
  stage: build
  image: python:3.11
  script:
    - echo "Building project..."
    - pip install -r requirements.txt
    - python setup.py build
    - python setup.py sdist
  artifacts:
    paths:
      - dist/
      - requirements.txt
    expire_in: 1 week

deploy:
  stage: deploy
  image: google/cloud-sdk:latest
  before_script:
    - echo "Setting up Google Cloud credentials..."
    - echo "$GOOGLE_CLOUD_KEY" > /tmp/key.json
    - gcloud auth activate-service-account --key-file=/tmp/key.json
    - gcloud config set project $GOOGLE_PROJECT_ID
  script:
    - echo "Deploying to web-server..."
    - apt-get update -qq
    - apt-get install -qq -y google-cloud-sdk
    - echo "Checking build artifacts..."
    - ls -la dist/
    - ls -la requirements.txt
    - echo "Creating target directory..."
    - gcloud compute ssh sa_kafka_test@$VM_NAME --zone=$GOOGLE_COMPUTE_ZONE --command="mkdir -p /home/sa_kafka_test/kafka-test"
    - echo "Copying files to VM..."
    - gcloud compute scp requirements.txt sa_kafka_test@$VM_NAME:/home/sa_kafka_test/kafka-test/ --zone=$GOOGLE_COMPUTE_ZONE
    - gcloud compute scp --recurse dist/* sa_kafka_test@$VM_NAME:/home/sa_kafka_test/kafka-test/ --zone=$GOOGLE_COMPUTE_ZONE
    - echo "Installing package on VM..."
    - gcloud compute ssh sa_kafka_test@$VM_NAME --zone=$GOOGLE_COMPUTE_ZONE --command="cd /home/sa_kafka_test/kafka-test && pip install -r requirements.txt && pip install *.tar.gz"
  only:
    - main 