version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - mouse-tracker-network

  # API сервер на Node.js для логирования координат мыши
  api:
    image: node:alpine
    volumes:
      - .:/app
      - ./logs:/app/logs
    working_dir: /app
    command: sh -c "mkdir -p /app/logs && node backend-mock.js"
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - mouse-tracker-network

# Создаем общую сеть для коммуникации между контейнерами
networks:
  mouse-tracker-network:
    driver: bridge 